### PR TITLE
chore: change about page's copy

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Fixes. https://github.com/web3-storage/web3.storage/issues/182

### CODE REVIEW

**Comment by jnthnvctr** [comment]
This looks good! Would we be able to make one other slight tweak? @terichadbourne  pointed out that there is a way we can enable Anchor links to each of the headers (e.g. Methodology) without having them actually be clickable links like Terms of Service. Would we be able to change the headers to do that? 

We definitely will want to be able to link to specific headers down the line, but we may not need to click on the link to just scroll down the page. 

Apologies if I'd described that ask poorly before!

**Review by jnthnvctr — COMMENTED** [review]
Can we tweak the headers such that they aren't clickable, but are anchor links still?

**Comment by alanshaw** [comment]
@jnthnvctr they should be clickable, people often click on headers and then copy the URL for sharing that part of the page. They should maybe not be underlined?

**Comment by rafaelramalho19** [comment]
I remove the linking part so far, tell me if you're satisfied with the current solution in the PR or if you wanna go with Alan's advice

**Comment by jnthnvctr** [comment]
Yeah thanks for this tweak - I just played with it - I think Mr. Shaw is
correct here

**Comment by rafaelramalho19** [comment]
Done :)

**Review by alanshaw — APPROVED** [review]

**Pull request merged**
