### PR TITLE
feat: Split file manager table into uploaded & pinned

### PR DESCRIPTION
**Pull request by svvimming**
This PR splits the file manager table into two tabs: Files uploaded directly and files uploaded through the pinning API.

completes #1254

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
(ignore, reviewed too early by accident, didn't see that this was a draft)

**Comment by svvimming** [comment]
The files manager table now retrieves a list of files pinned using the pinning API. The token for this request has to be one of the generated API tokens associated with the user, not a magic token. If none are available the request is not made and the pinned files table will be disabled and its tab is greyed out.

**Comment by orvn** [comment]
@dchoi27, before this is merged, I wanted to run the null case by you: if a user has nothing uploaded via the pinning API, should we hide that tab? 

Currently it's in a disabled state, but will always appear. On the one hand, it clutters up the UI (in a minor way), but on the other, it's useful to keep if you want to make people aware of the pining API in a more indirect way.

split-table-default

**Review by orvn — APPROVED** [review]
LGTM!

As a minor ux nit, in the future it might be good to alter the design such that it's super clear that the top-level items are tabs, not just headings.

**Pull request merged**
