### PR TITLE
fix: testimonial cards link behavior

### PR DESCRIPTION
**Pull request by svvimming**
A fix to update the index page testimonial cards with the correct behaviour outlined below:

If a card has a link in its description:

- Clicking anywhere on the card takes the user to that link (in a new tab)
- Hovering over the card shows the current glow effect
- The text that's linked should still be underscored (currently shown with a bottom border)

If the card does not have a link in its description:

- Hovering on the card does not produce the hover effect
- The card is not clickable

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
Looks good, but there's one issue where the `cursor: pointer` isn't working for some reason, maybe because the leaf nodes are being hovered on instead of the actual linked card

**Comment by svvimming** [comment]
@orvn fixed now, it was actually a before element from the following section that was covering part of the cards

**Comment by orvn** [comment]
@svvimming, I'm still seeing the issue? (tested on MacOS Firefox and Chrome)

**Review by orvn — APPROVED** [review]
Regression tested cross browser and this works in all instances.

**Pull request merged**
