### PR TITLE
Checkbox error handling

### PR DESCRIPTION
**Pull request by rafaelramalho19**
- Adds Alert component
- Shows extra details to the user when he tries to delete/select an upload that's still geting the dagsize calculated

Demo:

https://user-images.githubusercontent.com/24696635/133822963-9c6d572e-2b00-410b-85c4-a4fd76ec1c42.mov

### CODE REVIEW

**Comment by olizilla** [comment]
A user should be able to delete an upload even if the dagSize has not been calcuated yet. I don't think we want to prevent that. Is there an issue connected to this PR where I can read the backstory?

**Comment by olizilla** [comment]
@rafaelramalho19 the work here is good! my concern is just that I dont think we should need it. Also of note we are about to land changes that mean partial uploads will have their full dagSize set even while the other parts are still uploading, so we might need to rethink this.

@vasco-santos can you explain why we have this limitation? Why can't I delete before dagSize is calculated? Do we need some other flag to tell us when we have multiple partial dags still being processed.

**Comment by vasco-santos** [comment]
With the changes from unifying /upload and /car routes, we calculate dag size differently now https://github.com/web3-storage/web3.storage/pull/480

With this, the limitation to wait for dagSize to be computed should not exist anymore. Can you try and confirm @rafaelramalho19 ?

**Comment by rafaelramalho19** [comment]
> With the changes from unifying /upload and /car routes, we calculate dag size differently now #480
> 
> With this, the limitation to wait for dagSize to be computed should not exist anymore. Can you try and confirm @rafaelramalho19 ?

Good call @vasco-santos! Now it's not needed, closing this PR 😄

**Pull request closed without merging**
