### PR TITLE
fix: website 404

### PR DESCRIPTION
**Pull request by joannaong**
redirect 404 to appropriate 404 page. solves https://github.com/web3-storage/web3.storage/issues/478

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
It works! 🎉  Although now the docs 404 seems to be unstyled?

We should have it redirect to the next 404, or make the docs 404 similar to what's in Next

docs-404

**Comment by joannaong** [comment]
> It works! 🎉 Although now the docs 404 seems to be unstyled?
> 
> We should have it redirect to the next 404, or make the docs 404 similar to what's in Next
> 
> docs-404

fixed with latest commit

**Review by orvn — APPROVED** [review]
lgtm!

**Comment by orvn** [comment]
This closes a long standing issue #478 and unifies the 404 between the website and current docs. 

Appears to work on the build preview, so it should be good for the staging and production sites too.

**Pull request merged**
