### PR TITLE
fix: improve table layout inside files page

### LINKED ISSUE #430: Nowrap for timestamp, CID and pin status columns in files listing
The behavior looks correct to me, but you might have more context for this @alanshaw?

### LINKED ISSUE #431: Fix layout of top buttons on table layout on mobile
The line breaks create a weird button for "upload more files" and the spacing is off.
Files_-_Web3_Storage

@alanshaw

### PR DESCRIPTION
**Pull request by jdiogopeixoto**
- Improves the table inside the files page (with nowrap):

download

- Improves the buttons behavior on top of the table:

https://user-images.githubusercontent.com/34691925/132368917-c918a5e1-c1ee-4f7e-9af2-dd9db405dc4f.mov

- Adds some minor accessibility improvements

Closes #430
Closes #431

### CODE REVIEW

**Review by zebateira — APPROVED** [review]
LGTM 👍

**Comment by zebateira** [comment]
@atopal do we also want this change to be done to the tokens list and also shorten the token value and include a copy button? Maybe a separate issue?

**Comment by atopal** [comment]
@zebateira  Yes, makes a lot of sense. Would you mind filing a separate issue for that?

**Comment by zebateira** [comment]
@atopal done! #455

**Pull request merged**
