### PR TITLE
feat: support multiple gateway URLs

### PR DESCRIPTION
**Pull request by alanshaw**
This PR adds support for multiple gateway URLs in the API proxy. It allows us to ask freeway first, then fallback to `ipfs.io`.

### CODE REVIEW

**Review by vasco-santos — APPROVED** [review]
LGTM

Please set the Secret before merging and add it to README.md 🙏🏼

**Review by olizilla — COMMENTED** [review]
`GATEWAY_URL` is set in wrangler.toml so consider setting the new CSV var there too.

**Comment by olizilla** [comment]
@alanshaw good to go?

**Review by alanshaw — COMMENTED** [review]
🚢

**Pull request merged**
