### PR TITLE
fix: login screens jarring

### PR DESCRIPTION
**Pull request by drewdelano**
Closes https://github.com/web3-storage/web3.storage/issues/1440

Switches the "callback" route to product-app to fix the background

Uses flexbox to position the footer for product-app

### CODE REVIEW

**Comment by JeffLowe** [comment]
Visual inspection of the login flow on the preview link:
Look much better.  Login screen footer anchored at bottom so no whitespace under footer.  
The callback screen now uses the site's darker background and styled loader animation.  
@drewdelano Question:  Is there a way to change the white magic auth screen to darker color?  Is that something we have to do in magicauth settings (thus only someone with access can accomplish)?

**Comment by drewdelano** [comment]
I suspect so, but I can take a look too.

**Review by jsdevel — APPROVED** [review]

**Comment by JeffLowe** [comment]
@drewdelano dont let the magiclink screen block getting this pr's improvements out.  We can always circle back (in new ticket) to address the magiclink screen.

**Comment by drewdelano** [comment]
I talked with @JeffLowe about this on Slack.  I'm going to go ahead and merge this.  I'll fix the magic link bit in another ticket he's creating now.

**Pull request merged**
