### PR TITLE
feat: create page for service level agreement

### PR DESCRIPTION
**Pull request by drewdelano**
https://www.notion.so/create-page-for-service-level-agreement-SLA-ba8320a690864adea373892c4ed4db65

 - [x]  Link under Resources column on the footer
 - [x]  New page should be here: [https://web3.storage/sla/](https://web3.storage/sla/)
 - [x]  Clone from [https://web3.storage/terms/](https://web3.storage/terms/)

### CODE REVIEW

**Comment by drewdelano** [comment]
FYI - starting work on the SLA @gobengo @heyjay44

**Comment by drewdelano** [comment]
parking this while we wait for updated legal text

**Comment by drewdelano** [comment]
parking this while we wait for updated legal text

**Comment by drewdelano** [comment]
parking this while we wait for updated legal text

**Comment by drewdelano** [comment]
@cmunns @gobengo can I bother one of you for a review here?

**Review by gobengo — APPROVED** [review]

**Pull request merged**
