### PR TITLE
feat: add w3name http api swagger doc page

### PR DESCRIPTION
**Pull request by joshJarr**
Adds a page to host the http swagger docs for w3name API, fetching the schema from the w3name API. 

TODO: 

- [x] Test CORS
- [x] Validate the correct copy is in the open API docs
- [x] Test the API via the interactive docs, ensure the schemas are documented accurately

### CODE REVIEW

**Comment by joshJarr** [comment]
@yusefnapora Sorry, I've been a little slow getting this PR together as it was blocked by some of the openAPI work on W3Name.
I tried to copy a similar format to web3.storage but am not the best with words, would love your feedback on the OpenAPI docs and [swagger UI](https://bafybeih7wfqpecc74peqfvzt53egtbxpggzg4s6utmzr5vqbykbsptutqq.ipfs.w3s.link/docs/reference/w3name-http-api/
).

I moved the w3name API reference to it's own page and renamed the web3.storage api from HTTP API => web3.storage HTTP API so they won't be confused, do you think this is a good idea, or should we put the new w3name HTTP docs in a separate section since it's being treated as a separate product? 

Thanks!

**Comment by francois-potato** [comment]
Hey [@yusefnapora](https://github.com/yusefnapora), are you happy with the proposed changes? Here is the w3name HTTP API documentation in action: https://2e9ef0d8.web3-storage-staging.pages.dev/docs/reference/w3name-http-api/

**Comment by mbommerez** [comment]
Hi @yusefnapora / @dchoi27 , can you have a quick look at this and confirm if we can merge this?
Thanks!

**Review by francois-potato — APPROVED** [review]

**Comment by joshJarr** [comment]
re:WebSocket documentation:
it doesn't look trivial to document the WebSocket endpoint in swagger, would make sense to document this separately somehow.

**Pull request merged**
