### PR TITLE
chore: remove lingering faunadb refs & associated 'report' package

### PR DESCRIPTION
**Pull request by adamalton**
This is a new, tidier, simpler version of #1104, which turned into a bit of a mess. I'll close that PR in favour of this one.

* Removes lingering references to Fauna DB.
* Removes the deprecated 'report' package, which was built around Fauna DB and its GraphQL support.

### CODE REVIEW

**Comment by adamalton** [comment]
@olizilla or @alanshaw are either of you able to tell me what's happening in the failing Cloudflare Pages task here? I don't have access to be able to see details of the failing job.

**Comment by olizilla** [comment]
The CF Pages error doesn't appear to be releated to this PR.
```
...
17:07:56.292 | > @web3-storage/website@2.0.0 build
17:07:56.292 | > next build && next-sitemap && next export && ./scripts/docs.sh
17:07:56.292 |  
17:07:57.138 | warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
17:07:57.198 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
17:07:57.198 | This information is used to shape Next.js' roadmap and prioritize features.
17:07:57.198 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
17:07:57.198 | https://nextjs.org/telemetry
17:07:57.198 |  
17:07:57.259 | info  - Checking validity of types...
17:08:12.482 |  
17:08:12.482 | Failed to compile.
17:08:12.482 |  
17:08:12.482 | ./pages/404.js
17:08:12.482 | 1:1  Error: There should be at least one empty line between import groups  import/order
17:08:12.482 | 2:1  Error: There should be no empty line within import group  import/order
17:08:12.482 |  
17:08:12.482 | ./components/tokens/tokenCreator/tokenCreator.js
17:08:12.482 | 73:16  Warning: The ref value 'inputRef.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'inputRef.current' to a variable inside the effect, and use that variable in the cleanup function.  react-hooks/exhaustive-deps
17:08:12.482 |  
17:08:12.482 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
17:08:12.496 | npm ERR! Lifecycle script `build` failed with error:
17:08:12.496 | npm ERR! Error: command failed
17:08:12.496 | npm ERR!   in workspace: @web3-storage/website@2.0.0
17:08:12.496 | npm ERR!   at location: /opt/buildhome/repo/packages/website
17:08:12.507 | Failed: build command exited with code: 1

```

**Comment by vasco-santos** [comment]
> The CF Pages error doesn't appear to be releated to this PR.

Sometimes CF Pages randomly fails, it is a bit annoying

**Comment by alanshaw** [comment]
```
<pre class="c_nh c_bo c_mk c_ml c_om c_on c_cw c_pf c_ie c_ic c_id c_fn c_fo c_bq c_oo">

14:28:44.267 | Failed to compile.
-- | --
14:28:44.268 |  
14:28:44.268 | ./pages/404.js
14:28:44.268 | 1:1  Error: There should be at least one empty line between import groups  import/order
14:28:44.268 | 2:1  Error: There should be no empty line within import group  import/order
14:28:44.268 |  
14:28:44.268 | ./components/tokens/tokenCreator/tokenCreator.js
14:28:44.268 | 73:16  Warning: The ref value 'inputRef.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'inputRef.current' to a variable inside the effect, and use that variable in the cleanup function.  react-hooks/exhaustive-deps
14:28:44.268 |  
14:28:44.268 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
14:28:44.281 | npm ERR! Lifecycle script `build` failed with error:
14:28:44.282 | npm ERR! Error: command failed
14:28:44.282 | npm ERR!   in workspace: @web3-storage/website@2.0.0
14:28:44.282 | npm ERR!   at location: /opt/buildhome/repo/packages/website
14:28:44.294 | Failed: build command exited with code: 1

</pre>
```

Please rebase - I fixed this in https://github.com/web3-storage/web3.storage/pull/1204

@adamalton please can you open a PR to run the website build as part of the test procedure as we do here?: https://github.com/nftstorage/nft.storage/blob/21e8eb08962a36aa449d9d65e37631cfedcc672b/.github/workflows/website.yml#L13-L29 🙏🙏🙏

**Review by vasco-santos — APPROVED** [review]
LGTM

**Pull request merged**
