### PR TITLE
chore: add countly analytics integration for user tracking

### PR DESCRIPTION
**Pull request by zebateira**
Creating this PR for visibility of the work in progress.

- [x] Setup countly init
- [x] Track page views
- [x] Track 404s
     - Simple 404 page added for this
- [x] Track header and footer links
- [x] Track other links to docs and other pages
- [x] Track CTA clicks and other actions
     - [x] Login / Logout
     - [x] Files (Upload / Delete)
     - [x] Tokens (Create / Copy / Delete)
 
### Deployment

- [x] Add env vars to build #202 
     - `NEXT_PUBLIC_COUNTLY_KEY`
     - `NEXT_PUBLIC_COUNTLY_URL`

(Requirements [here](https://www.notion.so/protocollabs/storage-metrics-ee4ec19916e440e1aa3e3b0f2cc7030b#16d5bacaacd7431a8fc2caa1052fd372)).

### CODE REVIEW

**Comment by olizilla** [comment]
@zebateira how's this going? would be good to land it early this week.

**Comment by zebateira** [comment]
@olizilla ready for review!

**Comment by zebateira** [comment]
Note that I added a 404 page to be able to track 404s. Very basic, so let me know if you'd like any change on that.

**Comment by olizilla** [comment]
@alanshaw if you are eager to get deployed to prod, it'd be good to land this PR first. I can eyeball it later today, but if you have a moment, pls dig in.

**Comment by zebateira** [comment]
I just realized the 404 page is not working using `ipfs-404.html`. Was this recently changed? It doesn't seem to be working on fleek deployed sites as well (ipfs.io, blog.ipfs.io, docs.ipfs.io, proto.school, etc).

**Comment by zebateira** [comment]
aah, I think the problem is that the build is generating a `ipfs-404/index.html` file, not a `ipfs-404.html`!
On it.

**Comment by zebateira** [comment]
Ok fixed: generated the `ipfs-404.html` file with `exportPathMap` https://github.com/web3-storage/web3.storage/pull/126/commits/1c5bde118d52b368edefdbbd1348a4ef7185d53c
Good to go!

**Comment by terichadbourne** [comment]
@zebateira Just confirming that you've resolved the 404 issue and all merge conflicts and the only blocker here is a review from @olizilla or @alanshaw? 

**NOTE: We won't have any analytics from the main site for usage at the hackathon until this is merged. Likely to generate traffic starting with presos this afternoon.**

**Comment by zebateira** [comment]
@terichadbourne yap, all ready for review!

**Comment by olizilla** [comment]
@rafaelramalho19 my head is no deep on the website code, can review this PR please?

**Review by olizilla — APPROVED** [review]
Neat! Implementation looks good and I can see the countly events on the preview site https://bafybeigxve4jcuc5o5cq3sjifgw5ukzteb23xsqalzjltavk5bzn4bi3w4.ipfs.dweb.link/

@jnthnvctr can you propose a change to the about page or terms of service that explains to users what metrics / clicks we track and why, and what we do with the data?

**Comment by terichadbourne** [comment]
@olizilla just confirming - you still want @rafaelramalho19 to proof this in addition to you? Or shall we merge to get analytics rolling in and then have him take a pass tomorrow and make any suggested edits?

**Comment by olizilla** [comment]
Yes, @rafaelramalho19 has been leading the charge on the website work, so I'd like him to give it the once over. I'm ok with getting this deployed tomorrow.

**Review by rafaelramalho19 — APPROVED** [review]
LGTM, just make sure to fix the merge conflicts 👍

**Comment by zebateira** [comment]
Merge conflicts resolved!

**Pull request merged**
