### PR TITLE
docs: Fix broken link to Query guide

### PR DESCRIPTION
**Pull request by ajcwebdev**
There's currently a [broken link](https://web3.storage/docs/how-tos/query.md#querying-for-status-information) in the [intro page](https://web3.storage/docs/#run-the-script).

Screen Shot 2022-06-04 at 3 57 22 AM

Looks like this is because `.md` was included in the URL path. This makes the link work correctly in the GitHub repo but not on the actual generated site, so [removing `.md` should ensure the correct path is appended](https://web3.storage/docs/how-tos/query#querying-for-status-information).

### CODE REVIEW

**Review by drewdelano — APPROVED** [review]
LGTM

**Comment by drewdelano** [comment]
@ajcwebdev looks good, but you have some build failures from the look of it.  Can you fix those?

**Review by drewdelano — CHANGES_REQUESTED** [review]
@ajcwebdev looks good, but you have some build failures from the look of it. Can you fix those?

**Comment by ajcwebdev** [comment]
If I'm understanding correctly, the error `MISSING ENV. Please set NEXT_PUBLIC_MAGIC` is because I skipped this step:

> You need an account on magic.link, and Docker running locally. Copy the `<.env.tpl>` file to `.env` and set the values for the `MAGIC_SECRET_KEY` & `NEXT_PUBLIC_MAGIC`, from your magic.link account dashboard.

I'm not sure why making a one line change to a markdown file requires creating an account on magic.link and getting an API key. That's a rather large friction point that I don't believe I've seen before on any of the dozen or so similar PR's I've opened on other open source repositories. I'll close this out and you're welcome to copy paste the fix and have someone on your team commit and push the changes.

**Pull request closed without merging**
